### PR TITLE
Float Branch

### PR DESCRIPTION
**Pull request by luisrpavanelli**
in this pull request I am modifying it to float as requested by the project part four.

- Float  left in tags

### CODE REVIEW

**Review by shella12 — COMMENTED** [review]
Hi <STUDENT_MENTION>, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] Does not have any review performed. Please make sure to perform the review on you your project using the [guidelines.
](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by luisrpavanelli** [comment]
in this pull request I am modifying it to float as requested by the project part four.

Float left in tags

**Review by Zuhaib042 — COMMENTED** [review]
Hi @luisrpavanelli , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that Does not have any review performed. Please make sure to perform the review on you your project using the [guidelines.](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by adel-gu — COMMENTED** [review]
# Status: INVALID ❌ 

**Hi @luisrpavanelli 👋🏼** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

⬇️⬇️⬇️
You have submitted a project, without implementing the project requirement where you have to perform a **code review on your PR**, please refer to [Project Requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md).
🆙🆙🆙
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
