### PR TITLE
Sections branch

### PR DESCRIPTION
**Pull request by luisrpavanelli**
In this milestone, I achieved the following...

- added images and logo
- added parts of code in html file
- added code parts in css file
- added links and buttons

sections were included

- recent works section: multi-post stories
- section about me
- languages section
- frameworks section
- skills section

### CODE REVIEW

**Comment by luisrpavanelli** [comment]
In this milestone, I achieved the following...

- added images and logo
- added parts of code in html file
- added code parts in css file
- added links and buttons

sections were included

- recent works section: multi-post stories
- section about me
- languages section
- frameworks section
- skills section

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @luisrpavanelli 👋👋, 

tryagain


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [ ] Linters are passing👍
- [ ] Github flow has been used👍


## Required Changes ♻️

- [ ]  Nice job so far😉, There is just an issue😉 You still haven't given attention to your header hierarchy😉 for your works and about intro header, Kindly make use of a `h2` tag instead of a `h1` tag as we already used an `h1` tag for the main header of the page😊 this makes your code more semantic😎
HEADER hier111
header hiera222


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luisrpavanelli** [comment]
Hello, I did the suggestion, thank you so much

**Review by AlphaNtihinduka — CHANGES_REQUESTED** [review]
## Hi @luisrpavanelli 🙋‍♂️
Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

close

## Required changes :recycle: 
- As the previous reviewer suggested,  there is just an issue😉 You still haven't given attention to your header hierarchy😉 for your works and about intro header, Kindly make use of a `h2-h6` tags instead of a `h1` tag as we already used an `h1` tag for the main header of the page😊 this makes your code more semantic😎. Please apply the changes to the `sections` branch as it is the latest branch you are working on.
image

image

## Optional suggestions
- [ ] [OPTIONAL]  I suggest that when you checkout to the new branch and you have made a new PR, to ensure that you attach the old PR link in description of the new PR. This enables the  code reviewer to refer to the previous reviews done by other code reviewers ☺️ .


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

**Comment by luisrpavanelli** [comment]
Hello, I did the suggestions, thank you so much:

I use of a h2 tag instead of a h1 tag as we already used an h1 tag for the main header of the page.

**Review by MeqdamAlqudah — APPROVED** [review]
Hi @luisrpavanelli , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
image

## Highlights 
:+1: no linter errors 
:+1: semantic HTML structure

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
